config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  root to: 'mealplans#index'
  post 'user_token' => 'user_token#create'

  if Rails.env.development?
    mount Sidekiq::Web, at: 'sidekiq'
  end

  post '/graphql', to: 'graphql#execute'
  resources :recipes
  resources :ingredients
  resources :mealplans do
    resources :mealplan_completions, only: %i[create]
    resources :mealplan_reopenings, only: %i[create]
  end

  namespace 'api' do
    namespace 'v1' do
      resources :users
      resources :recipes
      resources :ingredients
    end
  end
end

app/models/recipe.rb
# frozen_string_literal: true

##
# Base Recipe model
##
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :ingredient_recipes
  has_many :ingredients, through: :ingredient_recipes, inverse_of: :recipes

  has_many :mealplan_recipes
  has_many :mealplans, through: :mealplan_recipes

  accepts_nested_attributes_for :ingredient_recipes

  validates :name, presence: true

  def estimated_price
    # TODO: Need to find a good way to use the quantity as a
    # multiplier
    ingredients.reduce(0) { |acc, ing| acc + ing.price }
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :require_user
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = current_user.recipes.includes(:ingredients)
  end

  def show; end

  def edit
    set_edit_params
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredient_recipes << IngredientRecipe.new
    @available_ingredients = current_user.ingredients
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    result = ::Services::Recipes::Create.new(
      recipe: @recipe,
      params: recipe_params
    ).call
    if result
      redirect_to recipes_path
    else
      flash_errors(@recipe.errors)
      render :new
    end
  end

  def update
    @recipe.user = current_user
    success = ::Services::Recipes::Update.new(
      recipe: @recipe,
      params: recipe_params
    ).call

    if success && @recipe.save
      redirect_to recipe_path(@recipe)
    else
      set_edit_params
      flash_errors(@recipe.errors)
      render :edit
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to recipes_path
    else
      render :show
    end
  end

  private

  def set_recipe
    @recipe = current_user.recipes
                          .includes(:ingredients, :ingredient_recipes)
                          .find(params[:id])
  end

  def set_edit_params
    @available_ingredients = ::Services::Recipes::MapAvailableIngredients
                             .new(recipe: @recipe, user_id: current_user.id)
                             .call
    @ingredients = ::Services::Recipes::MapIngredientsEditData
                   .new(recipe: @recipe).call
  end

  def recipe_params
    params.require(:recipe)
          .permit(:name,
                  :description,
                  ingredient_recipes_attributes: [
                    :ingredient_id,
                    :quantity
                  ])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe.erb
<div class="flex flex-col justify-between mb-8">
  <h3 class="font-bold text-xl">
    <%= link_to recipe.name, recipe_path(recipe) %>
  </h3>
  <div class="flex flex-row items-center justify-between">
    <div class="mt-2">
      <p class="mt-2">
        <%= recipe.description %>
      </p>
    </div>
    <div class="flex flex-row items-center justify-end mt-4">
      <%= button_to 'Delete', recipe_path(recipe), class: "btn bg-white text-red-600 cursor-pointer hover:text-red-800", method: :delete %>
      <%= button_to 'Edit', edit_recipe_path(recipe), class: "btn btn-teal mr-2", method: :get %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= form_for @recipe,
  html: {
    class: "form-container",
    data:
      { 'controller' => 'edit-recipe',
        'edit-recipe-available-ingredients' => @available_ingredients.to_json
      }
  } do |form| %>
  <h1>Edit Recipe</h1>
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-field" %>
  <%= form.label :description %>
  <%= form.text_area :description, class: "form-field" %>
  <div data-target="edit-recipe.ingredientGroup">
    <% @ingredients.each_with_index do |ingredient, i| %>
      <div data-target="edit-recipe.ingredient">
        <select
          class="form-field-inline bg-white text-text-gray-600 w-full md:w-auto"
          data-target="create-recipe.availableIngredients"
          name=<%="recipe[ingredient_recipes_attributes][#{i}][ingredient_id]"%>
        >
          <option value="<%= ingredient[:ingredient_id] %>">
            <%= ingredient[:name] %>
          </option>
          <% @available_ingredients.each do |available_ingredient| %>
            <option value="<%= available_ingredient.id %>">
              <%= available_ingredient.name %>
            </option>
          <% end %>
        </select>
        <input
          class="form-field-inline"
          type="number"
          step="1"
          min="1"
          name=<%= "recipe[ingredient_recipes_attributes][#{i}][quantity]" %>
          value=<%= ingredient[:quantity] %>
        />
        <button
          class="btn btn-indigo-rev text-blue font-bold text-lg"
          data-action="click->edit-recipe#removeIngredient"
        >
          -
        </button>
      </div>
    <% end %>
  </div>
  <button
    class="btn btn-indigo my-2"
    data-action="click->edit-recipe#addIngredient"
    data-target="edit-recipe.addIngredientButton"
  >
    Add Ingredient
  </button>
  <div class="flex items-center justify-between">
    <%= form.submit "Save", class: "btn btn-indigo btn-group-left flex-1" %>
    <%= link_to "Back", recipes_path, class: "btn btn-link btn-indigo-rev btn-group-right flex-1 text-center" %>
  </div>
  <template data-target="edit-recipe.ingredientTemplate">
    <div data-target="edit-recipe.ingredient">
      <select
        class="form-field-inline bg-white text-text-gray-600 w-full md:w-auto"
        data-target="edit-recipe.availableIngredients"
        name="recipe[ingredient_recipes_attributes][0][ingredient_id]"
      >
        <% @available_ingredients.each do |ingredient| %>
          <option value="<%= ingredient.id %>">
            <%= ingredient.name %>
          </option>
        <% end %>
      </select>
      <input
        class="form-field-inline"
        type="number"
        step="1"
        min="1"
        name="recipe[ingredient_recipes_attributes][0][quantity]"
      />
      <button
        class="btn btn-indigo-rev text-blue font-bold text-lg"
        data-action="click->edit-recipe#removeIngredient"
      >
        -
      </button>
    </div>
  </template>
<% end %>

app/views/recipes/index.html.erb
<div class="container px-2 pt-4 flex flex-col">
  <section class="card level">
    <div class="flex flex-row items-center justify-between">
      <h1 class="text-teal-900 text-xl font-bold">Recipes</h1>
      <%= link_to "New Recipe +", new_recipe_path, class: "btn btn-link btn-teal text-white" %>
    </div>
    <div class="px-2 my-4">
      <% @recipes.each do |recipe| %>
        <%= render 'recipe', recipe: recipe %>
      <% end %>
    </div>
  </section>
</div>

app/views/recipes/new.html.erb
<%= form_for @recipe,
  html: {
    class: "form-container",
    data:
      { 'controller' => 'create-recipe',
        'create-recipe-available-ingredients' => @available_ingredients.to_json
      }
  } do |form| %>
  <h1 class="font-bold text-xl text-gray-900">Create Recipe</h1>
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-field" %>
  <%= form.label :description %>
  <%= form.text_area :description, class: "form-field" %>
  <div data-target="create-recipe.ingredientGroup">
    <div>
      <select
        class="form-field-inline bg-white text-text-gray-600 w-full md:w-auto"
        data-target="create-recipe.availableIngredients"
        name="recipe[ingredient_recipes_attributes][0][ingredient_id]"
        data-tid="new-recipe-ingredient-select"
      >
        <% if !@available_ingredients.present? %>
          <span class="flex mx-auto my-2">No Ingredients Available</span>
        <% end %>
        <% @available_ingredients&.each do |ingredient| %>
          <option value="<%= ingredient.id %>">
            <%= ingredient.name %>
          </option>
        <% end %>
      </select>
      <input
        class="form-field-inline"
        type="number"
        step="1"
        min="1"
        name="recipe[ingredient_recipes_attributes][0][quantity]"
        data-tid="new-recipe-ingredient-input"
      />
      <button
        class="btn btn-indigo-rev text-blue font-bold text-lg"
        data-action="click->create-recipe#removeIngredient"
      >
        -
      </button>
    </div>
  </div>
  <button
    class="btn btn-indigo my-2"
    data-action="click->create-recipe#addIngredient"
  >
    Add Ingredient
  </button>
  <div class="btn-group flex items-center justify-between">
    <%= form.submit "Create", class: "btn btn-indigo btn-group-left flex-1" %>
    <%= link_to "Back", :back, class: "btn btn-link btn-indigo-rev btn-group-right flex-1 text-center" %>
  </div>
  <template data-target="create-recipe.ingredientTemplate">
    <div>
      <select
        class="form-field-inline bg-white text-text-gray-600 w-full md:w-auto"
        data-target="create-recipe.availableIngredients"
        name="recipe[ingredient_recipes_attributes][0][ingredient_id]"
        data-tid="new-recipe-ingredient-select"
      >
        <% if !@available_ingredients.present? %>
          <span class="flex mx-auto my-2">No Ingredients Available</span>
        <% end %>
        <% @available_ingredients&.each do |ingredient| %>
          <option value="<%= ingredient.id %>">
            <%= ingredient.name %>
          </option>
        <% end %>
      </select>
      <input
        class="form-field-inline"
        type="number"
        step="1"
        min="1"
        name="recipe[ingredient_recipes_attributes][0][quantity]"
        data-tid="new-recipe-ingredient-input"
      />
      <button
        class="btn btn-indigo-rev text-blue font-bold text-lg"
        data-action="click->create-recipe#removeIngredient"
      >
        -
      </button>
    </div>
  </template>
<% end %>

app/views/recipes/show.html.erb
<div class="container-md flex flex-col card">
  <h1 class="text-lg font-bold">
    <%= @recipe.name %>
  </h1>
  <h3 class="my-2 text-left">
    <%= @recipe.description %>
  </h3>
  <% @recipe.ingredient_recipes.each do |ingredient_recipe| %>
    <div>
      <strong>
        <%= "#{ingredient_recipe.ingredient_name}:" %>
      </strong>
      <%= "#{ingredient_recipe.quantity} #{ingredient_recipe.ingredient.unit}(s)" %>
    </div>
  <% end %>
  <h3 class="my-2 text-left">
    Estimated Price
    <%= number_to_currency(@recipe.estimated_price, precision: 2) %>
  </h3>
  <div class="flex flex-row mt-6 items-center my-2">
    <div class="visited:text-white text-center btn btn-group-left btn-indigo flex-1">
      <%= button_to 'edit', edit_recipe_path(@recipe), method: :get, class: 'bg-blue-500 text-white' %>
    </div>
    <div class="visited:text-white btn btn-group-right btn-red flex-1">
      <%= button_to "delete", @recipe, method: :delete, class: 'bg-red-500 text-white' %>
    </div>
  </div>
</div>