config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  root to: 'mealplans#index'
  post 'user_token' => 'user_token#create'

  if Rails.env.development?
    mount Sidekiq::Web, at: 'sidekiq'
  end

  post '/graphql', to: 'graphql#execute'
  resources :recipes
  resources :ingredients
  resources :mealplans do
    resources :mealplan_completions, only: %i[create]
    resources :mealplan_reopenings, only: %i[create]
  end

  namespace 'api' do
    namespace 'v1' do
      resources :users
      resources :recipes
      resources :ingredients
    end
  end
end

app/models/ingredient.rb
# frozen_string_literal: true

##
# Base Ingredient model
##
class Ingredient < ApplicationRecord
  belongs_to :user
  has_many :ingredient_recipes
  has_many :recipes, through: :ingredient_recipes, inverse_of: :ingredients

  validates :name, presence: true
  validates :price, presence: true
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

##
# Basic api controller for Ingredients CRUD actions
##
class IngredientsController < ApplicationController
  before_action :require_user

  # GET /ingredients
  # GET /ingredients.json
  def index
    require_user
    @ingredients = current_user.ingredients.includes(:recipes)
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = current_user.ingredients.find(params[:id])
  end

  def edit
    @ingredient = current_user.ingredients.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.user = current_user

    if @ingredient.save
      redirect_to ingredient_path(@ingredient)
    else
      flash_errors(@ingredient.errors)
      render 'new'
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    @ingredient = current_user.ingredients.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to ingredient_path(@ingredient)
    else
      flash_errors(@ingredient.errors)
      render 'update'
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = current_user.ingredients.find(params[:id])
    if @ingredient.destroy
      redirect_to ingredients_path
    else
      render 'show'
    end
  end

  private

  def ingredient_params
    params.require(:ingredient)
          .permit(:name, :description, :price, :recipes, :unit)
  end
end

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-gray-900 text-lg font-bold">
        <%= "#{pluralize(@ingredient.errors.count, "error")} prohibited this ingredient from being saved:" %>
      </h2>
      <ul>
        <% @ingredient.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <br/>
  <%= f.text_field :name, autofocus: true, placeholder: "Name", required: true, class: "form-field" %>
  <%= f.label :description %>
  <%= f.text_area :description, placeholder: "Description", class: "form-field" %>
  <%= f.label :price %>
  <br/>
  <%= f.number_field :price, placeholder: "Cost per unit", step: 0.01, required: true, class: "form-field" %>
  <%= f.label :unit %>
  <br/>
  <%= f.text_field :unit, placeholder: "Unit of measurement", required: true, class: "form-field" %>
  <div class="flex justify-between mt-4">
    <%= submit_tag locals[:save_text], class: "btn-group-left btn-indigo flex-1",
      data: { disable_with: "#{locals[:saving_text]}..." } %>
    <%= link_to 'Back', :back, class: 'btn-group-right btn-indigo-rev text-center flex-1' %>
  </div>
<% end %>

app/views/ingredients/_ingredient.erb
<div class="flex flex-col justify-between mb-8">
  <h3 class="font-bold text-xl">
    <%= link_to ingredient.name, ingredient_path(ingredient) %>
  </h3>
  <div class="mt-2">
    <p class="mt-2 text-gray-600">
      <%= ingredient.description %>
    </p>
  </div>
  <div class="flex flex-row mt-4 justify-between items-center">
    <div>
      <strong class="text-gray-900 mr-2"><%= number_to_currency(ingredient.price, precision: 2) %></strong>
      <span class="text-gray-900"><%= "per #{ingredient.unit}" %></span>
    </div>
    <div class="flex flex-row items-center justify-end">
      <%= button_to 'Delete', ingredient_path(ingredient), class: "btn bg-white text-red-600 cursor-pointer hover:text-red-800", method: :delete %>
      <%= button_to 'Edit', edit_ingredient_path(ingredient), class: "btn btn-teal mr-2", method: :get %>
    </div>
  </div>
</div>

app/views/ingredients/edit.html.erb
<div class="form-container">
  <h2 class="py-2 font-bold text-gray-900 text-xl">Edit Ingredient</h2>
  <%= render 'form', locals: { save_text: 'Update', saving_text: 'Updating' } %>
</div>

app/views/ingredients/index.html.erb
<div class="container px-2 pt-4 flex flex-col">
  <section class="card level">
    <div class="flex flex-row items-center justify-between">
      <h1 class="text-teal-900 font-bold text-xl">Ingredients</h1>
      <%= link_to "New Ingredient +", new_ingredient_path, class: "btn btn-link btn-teal text-white" %>
    </div>
    <section class="px-2 my-4">
      <% @ingredients.each do |ingredient| %>
        <%= render 'ingredient', ingredient: ingredient %>
      <% end %>
    </section>
  </section>
</div>

app/views/ingredients/new.html.erb
<div class="form-container">
  <h2 class="py-2 font-bold text-xl text-gray-900">New Ingredient</h2>
  <%= render 'form', locals: { save_text: 'Create', saving_text: 'Creating...' } %>
</div>

app/views/ingredients/show.html.erb
<div class="container-md flex flex-col card">
  <h1 class="text-lg font-bold">
    <%= @ingredient.name %>
    <h3 class="my-2">
      <%= @ingredient.description %>
    </h3>
    <h3 class="my-2">
      <%= "#{number_to_currency(@ingredient.price, precision: 2)} per #{@ingredient.unit}" %>
      <div class="flex flex-row mt-6 w-full items-center">
        <div class="visited:text-white text-center btn btn-group-left btn-indigo flex-1">
          <%= button_to 'edit', edit_ingredient_path(@ingredient), class: 'bg-blue-500 text-white', method: :get %>
        </div>
        <div class="visited:text-white text-center btn btn-group-right btn-red flex-1">
          <%= button_to "delete", @ingredient, method: :delete, class: 'bg-red-500 text-white' %>
        </div>
      </div>
    </h3>
  </h1>
</div>