config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  root to: 'mealplans#index'
  post 'user_token' => 'user_token#create'

  if Rails.env.development?
    mount Sidekiq::Web, at: 'sidekiq'
  end

  post '/graphql', to: 'graphql#execute'
  resources :recipes
  resources :ingredients
  resources :mealplans do
    resources :mealplan_completions, only: %i[create]
    resources :mealplan_reopenings, only: %i[create]
  end

  namespace 'api' do
    namespace 'v1' do
      resources :users
      resources :recipes
      resources :ingredients
    end
  end
end

app/models/mealplan.rb
# frozen_string_literal: true

##
# Top-level class for mealplan, a collection of recipes
##
class Mealplan < ApplicationRecord
  belongs_to :user
  has_many :mealplan_recipes
  has_many :recipes, through: :mealplan_recipes
  accepts_nested_attributes_for :mealplan_recipes

  VALID_STATUSES = %w[
    pending
    completed
  ].freeze

  validates :status, inclusion: { in: VALID_STATUSES }
  validates :name, presence: true

  def complete
    self.status = 'completed'
    save
  end

  def reopen
    self.status = 'pending'
    save
  end

  def pending?
    status == 'pending'
  end

  def completed?
    status == 'completed'
  end

  scope :pending, -> { where(status: 'pending') }
  scope :completed, -> { where(status: 'completed') }
end

app/controllers/mealplans_controller.rb
# frozen_string_literal: true

###
# Top Level Mealplan class that contains recipes
# over time
##
class MealplansController < ApplicationController
  before_action :require_user

  DEFAULT_ERROR_MESSAGE = 'Something went wrong'

  def index
    @mealplans = mealplans
    @showing_completed = params[:completed]
  end

  def show
    @mealplan = mealplan
  end

  def new
    @mealplan = Mealplan.new
    @available_recipes = current_user.recipes
  end

  def edit
    @mealplan = mealplan
  end

  def create
    result = Services::Mealplans::Create.new(params: mealplan_params,
                                             user: current_user,
                                             recipe_ids: create_recipe_ids).call
    if result.failed?
      redirect_to new_mealplan_path, alert: result.error_message
    else
      redirect_to mealplans_path,
                  notice: 'Mealplan was successfully created.'
    end
  end

  def update
    if mealplan.update(mealplan_params)
      redirect_to mealplan, notice: 'Mealplan was successfully updated.'
    else
      flash_errors
      redirect_to edit_mealplan_url(mealplan)
    end
  end

  def destroy
    if mealplan.destroy
      redirect_to mealplans_url, notice: 'Mealplan was successfully destroyed.'
    else
      flash[:alert] = mealplan&.errors&.full_message || DEFAULT_ERROR_MESSAGE
      redirect_to mealplan_url(mealplan)
    end
  end

  private

  def mealplans
    @mealplans = if params[:completed]
                   current_user.mealplans.completed.includes(:recipes)
                 else
                   current_user.mealplans.pending.includes(:recipes)
                 end
  end

  def mealplan
    @mealplan ||= current_user.mealplans
                              .includes(:recipes, :mealplan_recipes)
                              .find(params[:id])
  end

  def mealplan_params
    params.require(:mealplan)
          .permit(:completed,
                  :name,
                  :notes,
                  :user,
                  mealplan_recipes_attributes: :id)
  end

  def create_recipe_ids
    mapped_ids = params.dig('mealplan', 'mealplan_recipes_attributes')
          &.values
          &.map { |v| v['id'] }

    mapped_ids || []
  end
end

app/helpers/mealplans_helper.rb
# frozen_string_literal: true

module MealplansHelper
  def self.friendly_date(date)
    date.strftime('%B %d, %Y')
  end
end

app/views/mealplans/_form.html.erb
<div class="w-3/5">
  <%= form_for mealplan, data: { controller: 'mealplan-form' },
               html: { class: 'flex flex-col'} do |f| %>
    <% if mealplan.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= "#{pluralize(mealplan.errors.count, "error")} prohibited this mealplan from being saved:" %>
        </h2>
        <ul>
          <% mealplan.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :name, class: 'mt-6 font-bold' %>
    <%= f.text_field :name, class: 'form-field', required: true %>
    <% if @available_recipes.present? %>
      <%= f.label :recipes, class: 'mt-6 font-bold' %>
      <select class="form-field my-2" data-target="mealplan-form.recipeSelect">
        <% @available_recipes.each_with_index do |recipe, i| %>
          <option name="recipes[<%= i %>]" value="<%= recipe.id %>">
            <%= recipe.name %>
          </option>
        <% end %>
      </select>
      <button class="btn btn-indigo w-full my-2" data-action="mealplan-form#addNewRecipe" type="button">
        Add
      </button>
      <ul data-target="mealplan-form.recipeList py-6"></ul>
    <% else %>
      <h3 class="font-bold text-gray-700 text-center py-2">No recipes yet</h3>
    <% end %>
    <%= f.label :notes, class: 'mt-6 font-bold' %>
    <%= f.text_area :notes, class: 'form-field' %>
    <div class="actions flex justify-between mt-6 text-center">
      <%= f.submit 'Save', class: 'btn-indigo btn-group-left flex-1' %>
      <%= link_to 'Back', :back, class: 'btn-indigo-rev btn-group-right flex-1' %>
    </div>
  <% end %>
</div>

app/views/mealplans/_mealplan.erb
<div class="flex flex-col justify-between">
  <h3>
    <%= link_to mealplan do %>
      <span>Mealplan for week of</span>
      <strong><%= MealplansHelper.friendly_date(mealplan.created_at) %></strong>
    <% end %>
  </h3>
  <div class="mt-2">
    <div>
      <%= link_to 'Destroy', mealplan, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-red-rev text-white btn-link' %>
    </div>
    <div class="font-bold flex flex-row items-center justify-end">
      <%= link_to 'Delete', mealplan_path(mealplan),
        class: 'btn text-red-500 hover:text-red-600 hover:bg-gray-100',
        method: :delete %>
      <%= link_to 'Edit', edit_mealplan_path(mealplan), class: 'btn btn-link text-indigo-600 hover:text-indigo-600 hover:bg-gray-100' %>
      <% if mealplan.pending? %>
        <%= button_to 'Complete',
                    mealplan_mealplan_completions_path(mealplan),
                    class: 'btn btn-link btn-teal text-white mx-2' %>
      <% end %>
      <% if mealplan.completed? %>
        <%= button_to 'Reopen',
                    mealplan_mealplan_reopenings_path(mealplan),
                    class: 'btn btn-link btn-teal text-white mx-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/mealplans/edit.html.erb
<h1>Editing mealplan</h1>
<%= render partial: 'form', locals: { mealplan: @mealplan } %>
<%= link_to 'Show', @mealplan %>
<%= link_to 'Back', mealplans_path %>

app/views/mealplans/index.html.erb
<% status = @showing_completed ? 'completed' : 'pending' %>
<div class="container px-2 pt-4 flex flex-col">
  <section class="card level">
    <div class="flex flex-row items-center justify-between">
      <span class="flex flex-col md:flex-row items-baseline">
        <h1 class="font-bold text-teal-900 text-xl mr-4">Mealplans</h1>
        <% if @showing_completed %>
          <%= link_to 'Show Pending', mealplans_path, class: 'text-blue' %>
        <% else %>
          <%= link_to 'Show Completed', mealplans_path + '?completed=true', class: 'text-blue' %>
        <% end %>
      </span>
      <%= link_to 'New Mealplan +', new_mealplan_path, class: 'btn btn-link btn-teal text-white my-auto' %>
    </div>
    <div class="px-2 my-4">
      <% @mealplans.each do |mealplan| %>
        <%= render 'mealplan', mealplan: mealplan %>
      <% end %>
      <% if @mealplans.length.zero? %>
        <p class="font-bold text-base">No <%= status %> mealplans</p>
      <% end %>
    </div>
  </section>
</div>

app/views/mealplans/new.html.erb
<div class="form-container w-3/5 items-center justify-center">
  <h1 class="font-bold text-gray-900 text-xl text-center">New mealplan</h1>
  <%= render partial: 'form', locals: { mealplan: @mealplan, available_recipes: @available_recipes } %>
</div>

app/views/mealplans/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<%= link_to 'Edit', edit_mealplan_path(@mealplan) %>
<%= link_to 'Back', mealplans_path %>