config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  root to: 'mealplans#index'
  post 'user_token' => 'user_token#create'

  if Rails.env.development?
    mount Sidekiq::Web, at: 'sidekiq'
  end

  post '/graphql', to: 'graphql#execute'
  resources :recipes
  resources :ingredients
  resources :mealplans do
    resources :mealplan_completions, only: %i[create]
    resources :mealplan_reopenings, only: %i[create]
  end

  namespace 'api' do
    namespace 'v1' do
      resources :users
      resources :recipes
      resources :ingredients
    end
  end
end

app/views/layouts/_navbar.html.erb
<div class="bg-teal-200 py-4 px-2 text-teal-800">
  <div class="flex items-center justify-between flex-wrap">
    <h3>
      <%= link_to "Mealplanner", root_url, class: "brand-name" %>
    </h3>
    <% if user_signed_in? %>
      <div class="flex items-center justify-between w-full md:w-auto md:justify-end">
        <%= link_to "Ingredients", ingredients_path, class: "home-link pr-2 md:px-4" %>
        <%= link_to "Recipes", recipes_path, class: "home-link pr-2 md:px-4" %>
        <%= link_to "Mealplans", mealplans_path, class: "home-link pr-2 md:px-4" %>
        <%= link_to "Sign Out", destroy_user_session_path,
          class: "home-link font-normal pr-2 md:px-4" %>
      </div>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "home-link pr-2 md:px-4" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta content="width=device-width,initial-scale=1.0" name="viewport"/>
    <link href="https://fonts.googleapis.com/css?family=Barlow" rel="stylesheet"></link>
    <title>Mealplanner</title>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body class="text-base">
    <%= csrf_meta_tag %>
    <% if flash[:notice] %>
      <div class="notice" data-controller="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert" data-controller="flash">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <% if flash[:success] %>
      <div class="success" data-controller="flash">
        <%= flash[:success] %>
      </div>
    <% end %>
    <%= render "layouts/navbar" %>
    <div class="flex flex-col items-center">
      <%= yield %>
      </div>
  </body>
</html>